courses/urls.py
from django.urls import path
from . import views

app_name='course'

urlpatterns = [ 
    path('mine/',views.ManageCourseListView.as_view(),name='manage_course_list'),
    path('create/',views.CourseCreateView.as_view(),name='course_create'),
    path('<pk>/edit/',views.CourseUpdateView.as_view(),  name='course_edit'),
    path('<pk>/delete/',views.CourseDeleteView.as_view(),name='course_delete'), 
    path('<pk>/module/',views.CourseModuleUpdateView.as_view(),name='course_module_update'),

    path('module/<int:module_id>/content/<model_name>/create/',views.ContentCreateUpdateView.as_view(),name='module_content_create'), 
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(),name='module_content_update'),
    path('content/<int:id>/delete/',views.ContentDeleteView.as_view(),name='module_content_delete'),
    path('module/<int:module_id>/',views.ModuleContentListView.as_view(),name='module_content_list'),
    path('',views.CourseListView.as_view(),name='course_list'),
    path('subject/<slug:subject>/',views.CourseListView.as_view(),name='course_list_subject'),
    path('<slug:slug>/',views.CourseDetailView.as_view(),name='course_detail'),
    
    ]

e_learnning/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/',include('courses.urls',namespace='course')),
    path('accounts/login/',auth_views.LoginView.as_view(),name='login'),
    path('accounts/logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('students/', include('students.urls')), 
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

courses/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.auth.models import User
from .fields import OrderField
from django.template.loader import render_to_string

class Subject(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100,unique=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering=['title']

class Course(models.Model):

    owner=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_courses')
    subject=models.ForeignKey(Subject,on_delete=models.CASCADE,related_name='courses')
    students=models.ManyToManyField(User,related_name='courses_joined',blank=True)

    title=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200,unique=True)

    overview=models.TextField()
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


    class Meta:
        ordering=['-created']    

class Module(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE,related_name='modules')
    title=models.CharField(max_length=200)
    description=models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])


    def __str__(self):
        return f'{self.order}_{self.title}'
    class Meta:
        ordering=['order']

class Content(models.Model):
    module=models.ForeignKey(Module,on_delete=models.CASCADE,related_name='contents')
    content_type=models.ForeignKey(ContentType,on_delete=models.CASCADE,limit_choices_to={'model__in':('Text','Image','Video','File')})
    object_id=models.PositiveIntegerField()
    item=GenericForeignKey('content_type','object_id')
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering=['order']



class ItemBase(models.Model):
    owner=models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_related')
    title=models.CharField(max_length=200)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string(f'courses/content/{self._meta.model_name}.html',{'item': self})


class Text(ItemBase):
    content=models.TextField()

class Image(ItemBase):
    image=models.ImageField(upload_to='images')

class File(ItemBase):
    file=models.FileField(upload_to='files')

class Video(ItemBase):
    url=models.URLField()
    

courses/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Course,Module

ModuleFormSet=inlineformset_factory(Course,Module,fields=['title','description'],extra=2,can_delete=True)

courses/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView
from django.views.generic.base import TemplateResponseMixin,View
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from .models import Course,Module,Content,Subject
from .forms import ModuleFormSet
from django.forms.models import modelform_factory
from django.apps import apps
from django.db.models import Count
from students.forms import CourseEnrollForm
# Create your views here.




    
class OwnerMixin:
    def get_queryset(self):
        qs=super().get_queryset()
        return qs.filter(owner=self.request.user)

class OwnerEditMixin:
    def form_valid(self, form):
        form.instance.owner=self.request.user
        return super().form_valid(form)

class OwnerCourseMixin(OwnerMixin,LoginRequiredMixin,PermissionRequiredMixin):
    model=Course
    fields=['subject','title','slug','overview']
    success_url=reverse_lazy('course:manage_course_list')

class OwnerCourseEditMixin(OwnerCourseMixin,OwnerEditMixin):
    template_name='courses/form.html'
    



class ManageCourseListView(OwnerCourseMixin,ListView):
    template_name='courses/list.html'
    permission_required='courses.view_course'

class CourseCreateView(OwnerCourseEditMixin,CreateView):
    permission_required='courses.add_course'

class CourseUpdateView(OwnerCourseEditMixin,UpdateView):
    permission_required='courses.update_course'

class CourseDeleteView(OwnerCourseMixin,DeleteView):
    template_name='courses/delete.html'
    permission_required='courses.delete_course'

class CourseModuleUpdateView(TemplateResponseMixin,View):
    template_name='courses/formset.html'
    course=None
    


    def get_formset(self,data=None):
        return ModuleFormSet(instance=self.course,data=data)

    def dispatch(self,request,pk):
        self.course=get_object_or_404(Course,id=pk,owner=self.request.user)
        return super().dispatch(request,pk)

    def get(self,request,*args, **kwargs):
        formset=self.get_formset()
        return self.render_to_response({'course':self.course,'formset':formset})
    
    def post(self,request,*args, **kwargs):
        formset=self.get_formset(data=request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('course:manage_course_list')
        return self.render_to_response({'course':self.course,'formset':formset})

    
    
    

class ContentCreateUpdateView(TemplateResponseMixin,View):
    module=None
    model=None
    obj=None
    template_name='courses/content_form.html'

    def get_model(self,model_name):
        if model_name in ['text','video','image','file']:
            return apps.get_model(app_label='courses',model_name=model_name)
        return None

    def get_form(self,model,*args, **kwargs):
        Form=modelform_factory(model=model,exclude=['owner','order','created','updated'])
        return Form(*args, **kwargs)

    def dispatch(self, request,module_id,model_name,id=None):
        self.module=get_object_or_404(Module,id=module_id,course__owner=request.user)
        self.model=self.get_model(model_name)
        if id:
            self.obj=get_object_or_404(self.model,id=id,owner=request.user)
        return super().dispatch(request,module_id,model_name,id)
    
    def get(self, request, module_id, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({'form': form, 'object': self.obj})

    def post(self,request,module_id,model_name,id=None):
        form=self.get_form(self.model,instance=self.obj,data=request.POST,files=request.FILES)
        if form.is_valid():
            obj=form.save(commit=False)
            obj.owner=request.user
            obj.save()
            if not id:
                Content.objects.create(module=self.module,item=obj)
            return redirect('course:module_content_list',self.module.id)
        return self.render_to_response({'form':form,'object':self.obj})


class ContentDeleteView(View):
    def post(self,request,id):
        content=get_object_or_404(Content,id=id,module__course__owner=request.user)
        module=content.module
        content.item.delete()
        content.delete()
        return redirect('course:module_content_list', module.id)


class ModuleContentListView(TemplateResponseMixin,View):
    template_name='courses/module_list.html'
    def get(self,request,module_id):
        module=get_object_or_404(Module,id=module_id,course__owner=request.user)
        return self.render_to_response({'module':module})

        

class CourseListView(TemplateResponseMixin,View):
    template_name='courses/courses_list.html'
    model=Course

    def get(self,request,subject=None):
        subjects=Subject.objects.annotate(total_courses=Count('courses'))
        courses=Course.objects.annotate(total_modules=Count('modules'))
        if subject:
            subject=get_object_or_404(Subject,slug=subject)
            courses=courses.filter(subject=subject)
        return self.render_to_response({'courses':courses,'subjects':subjects,'subject':subject})


class CourseDetailView(DetailView):
    model=Course
    template_name='courses/courses_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CourseEnrollForm(initial={'course':self.object})
        return context
    

templates/courses/content_form.html
{% extends 'base.html' %}


{% block title %}
    
    {% if object %}
        Edit- "{{object.title}}"
    {% else %}
    Add a new content
    {% endif %}
        
{% endblock title %}



{% block content %}
{% if object %}
Edit- "{{object.title}}"
{% else %}
Add a new content
{% endif %}
<h2>Course Info</h2>
<form action="" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save Content</button>
</form>
{% endblock content %}
    
    
    

templates/courses/courses_detail.html
{% extends "base.html" %}
{% block title %}  {{ object.title }} {% endblock %}
{% block content %}
  {% with subject=object.subject %} 
     <h1>      {{ object.title }}    </h1>
         <div class="module">
                  <h2>Overview</h2>
                        <p> 
                                   <a href="{% url "course:course_list_subject" subject.slug %}">        {{ subject.title }}</a>. 
                                          {{ object.modules.count }} modules.        Instructor: {{ object.owner.get_full_name }} 
                                             </p>      {{ object.overview|linebreaks }}
                                                </div> 
                                                 {% endwith %}

                                                 {% if request.user.is_authenticated %} 
                                                  <form action="{% url "student_enroll_course" %}" method="post">
                                                        {{ form }}
                                                            {% csrf_token %} 
                                                               <input type="submit" value="Enroll now"> 
                                                             </form> 
                                                             {% else %} 
                                                              <a href="{% url "student_registration" %}" class="button"> 
                                                                   Register to enroll  </a> 
                                                                   {% endif %}

{% endblock %}

templates/courses/courses_list.html
{% extends 'base.html' %}


{% block title %}

{% if subject %}
{{subject.title}} courses
{% else %}
All Courses
{% endif %}
    
    
{% endblock title %}




{% block content %}
    

{% if subject %}
{{subject.title}} Courses
 {% else %}
 All Courses   
{% endif %}
    <h3>subjects</h3>
    <ul>

{% for s in subjects %}
    <li>
        <a href="{% url 'course:course_list_subject' s.slug %}">{{s.title}}</a>
        <br>
        <span>
            {{s.total_courses}} course {{s.total_courses|pluralize}}
        </span>
    </li>
{% endfor %}
    
    </ul>

    
    {% for course in courses %}
    
    {% with subject=course.subject %}
    <h3>
        <a href="{% url 'course:course_detail' course.slug %}">{{course.title}}</a>
    </h3>
    <p>
        <a href="{% url 'course:course_list_subject' subject.slug %}">{{subject}}</a>
        {{course.total_modules}} modules
        Instructor : {{ course.owner.username }}
    </p>
        
    {% endwith %}
        
        
    {% endfor %}
        
{% endblock content %}
    

    

templates/courses/delete.html
{% extends 'base.html' %}

{% block title %}
     course Delete
{% endblock title %}

{% block content %}
    <h1>Delete course {{object}}</h1>
    <form action="{% url 'course:course_delete' object.id  %}" method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
{% endblock content %}
    

    

templates/courses/form.html
{% extends 'base.html' %}

{% block title %}
   
   {% if object %}
   Edit course "{{object.title}}"
    {% else %}
    create a new course

   {% endif %}
    
{% endblock title %}
    

{% block content %}
{% if object %}
Edit course "{{object.title}}"
 {% else %}
 create a new course

{% endif %}


    <form action="" method="post" autocomplete="off" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"> save course</button>
    </form>
{% endblock content %}
    

templates/courses/formset.html
{% extends 'base.html' %}

{% block title %}
    Edit-"{{course.title}}"
{% endblock title %}

{% block content %}
<h1>Edit-"{{course.title}}"</h1>
    <h2>Course Module</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{formset.as_p}}
        {{ formset.management_form }}
        <button type="submit">Save Module</button>
    </form>
{% endblock content %}
    
    

templates/courses/list.html
{% extends 'base.html' %}
{% block title %}
   {{ block.super }}-courses
{% endblock title %}


{% block content %}
    <h1>My Courses </h1>    
    
    {% for course in object_list %}
        {{course.title}} 
        <p>
            <a href="{% url 'course:course_edit' course.id %}">edit</a><br>
            <a href="{% url 'course:course_delete' course.id %}">delete</a><br>
            <a href="{% url 'course:course_module_update' course.id %}"> Edit Modules</a>
        </p>    
        
    {% empty %}
        <p>You haven't created any courses yet.</p>
    {% endfor %}

    <p>
        <a href="{% url 'course:course_create' %}">Create Course</a>
    </p>
        
{% endblock content %}
    

templates/courses/module_list.html
{% extends 'base.html' %}
{% load course %}

{% block title %}
    Module {{module.order|add:1}} : {{module.title}}
{% endblock title %}
    


{% block content %}
    
    {% with course=module.course %}
        <h1>
            Course {{course.title}}
        </h1>
        <h3>Modules</h3>
        
        {% for m in course.modules.all %}
            <ul>
                <li>
                <a href="{% url 'course:module_content_list' m.id %}">
                    <span>Module <span class="order">{{ m.order|add:1 }}</span> 
                    </span>
                    <br>
                    {{ m.title }}
                </a>
            </li>
        </ul>
        {% empty %}
        No modules Yet
        {% endfor %}
        <p><a href="{% url "course:course_module_update" course.id %}">    Edit modules</a></p>
        <h2>Module {{ module.order|add:1 }}: {{ module.title }}</h2>    <h3>Module contents:</h3>
        
        {% for content in module.contents.all %}
            
            {% with item=content.item  %}
            <p>{{item}} {{item|model_name}}</p>
            <a href="{% url "course:module_content_update" module.id item|model_name item.id %}">  Edit </a>
            <form action="{% url 'course:module_content_delete' content.id %}" method="post">
                {% csrf_token %}
                <button type="submit">Delete</button>
            </form>
                
            {% endwith %}
            {% empty%}
            <p>This module has no contents yet.</p> 
        {% endfor %}

        <h3>Add new content:</h3> 
        <ul class="content-types">
                  <li>
                            <a href="{% url "course:module_content_create" module.id "text" %}"> 
                                         Text        </a> 
                                             </li>
                                                   <li> 
                            <a href="{% url "course:module_content_create" module.id "image" %}">
                                          Image        </a> 
                                             </li>
                                                   <li> 
                             <a href="{% url "course:module_content_create" module.id "video" %}">
                                          Video        </a>
                                              </li> 
                                                   <li> 
                            <a href="{% url "course:module_content_create" module.id "file" %}">
                                          File        </a>
                           </li> 
            </ul>
            
    {% endwith %}
        
{% endblock content %}
    

templates/courses/student_course_detail.html
{% extends "base.html" %}
{% block content %}  <h1>    {{ module.title }}  </h1>  <div class="contents">    <h3>Modules</h3>    <ul id="modules">      {% for m in object.modules.all %}        <li data-id="{{ m.id }}" {% if m == module %}class="selected"{% endif %}>          <a href="{% url "student_course_detail_module" object.id m.id %}">            <span>              Module <span class="order">{{ m.order|add:1 }}</span>            </span>            <br>            {{ m.title }}          </a>        </li>      {% empty %}        <li>No modules yet.</li>      {% endfor %}    </ul>  </div>  <div class="module">    {% for content in module.contents.all %}      {% with item=content.item %}        <h2>{{ item.title }}</h2>        {{ item.render }}      {% endwith %}    {% endfor %}  </div> {% endblock %}

templates/courses/student_course_list.html
{% extends "base.html" %}
{% block title %}My courses{% endblock %}
{% block content %}
  <h1>My courses</h1>
    <div class="module">
            {% for course in object_list %}
        <div class="course-info">
        <h3>{{ course.title }}</h3> 
       <p><a href="{% url "student_course_detail" course.id %}"> 
               Access contents</a></p>  
                </div>    {% empty %} 
                     <p> 
                               You are not enrolled in any courses yet.  
                                     <a href="">Browse courses</a>
                                             to enroll on a course.      </p>
                                                 {% endfor %}
                                                  </div>
                                                   {% endblock %}